### PR TITLE
Remove FFI wrappers around methods deleted from Z3

### PR DESCRIPTION
**Pull request by tchajed**

### CODE REVIEW

**Comment by tchajed** [comment]
@philnguyen this gets z3-rkt working again with the latest version of Z3 (including master) - could you take a look? Thanks!

**Comment by philnguyen** [comment]
Thanks @tchajed ! I was a bit worried about breaking compatibility if somebody relied on the old API (not that this package has many users). I decided on a compromise that on newer versions of Z3 where it can't find the function for the name, it'll generate a dummy function that throws an error when invoked.

For example, if you ever call the function `parse-smtlib-string!` on a newer Z3 library that has actually removed it, you'll get an error:
```
`parse-smtlib-string!` needs Z3 not after 4.5.0. Detected version is 4.8.4
```
But otherwise you won't get an error just by loading the library. Will this work for you?

**Comment by philnguyen** [comment]
If this solution works for you, I've annotated all bindings that you removed as needing Z3 not after `4.5.0` in 78deda2c7a377b9

**Comment by tchajed** [comment]
Yup, that works for me, thanks!

**Pull request closed without merging**
